apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: 2018-12-19T10:03:00Z
  name: devicerepo-deployment
  namespace: default
  labels: 
     app: nuviot
     teir: serviceproviders
spec:
  replicas: 1     
  selector:
    matchLabels:
      app: nuviot
      teir: serviceproviders
  template:
    metadata:
      labels:
        app: nuviot
        teir: serviceproviders
        service: devicerepo
    spec:
      containers:
      - name: devicerepo
        image: nuviot/devicerepo:v1.6.585.1631
        env:
          - name: AccessKey
            valueFrom: 
              secretKeyRef:
                name: instance-secrets
                key: AccessKey
        envFrom:
          - configMapRef:
              name: instance-settings
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: docker-repo-secret     
