apiVersion: v1
kind: Service
metadata:
    name: open-redis-slave
spec:
    type: NodePort
    ports:
        - targetPort: 6379
          port: 6379
          nodePort: 30015
    selector:
        app: redis
        role: slave
        tier: backend