apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-12-19T10:03:00Z
  name: settings-service
  namespace: default
  labels: 
     app: nuviot
     teir: serviceproviders
spec:
  ports: 
    - port: 80      
  selector:
     app: nuviot
     teir: serviceproviders
     service: settings